name: notes_app
description: A Flutter notes app with Firebase authentication and Firestore integration.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies - Updated versions
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_auth_web: ^5.15.2
  cloud_firestore: ^5.6.11
  cloud_firestore_web: ^4.4.11
  js: ^0.7.2
  # State management - Updated version
  flutter_bloc: ^9.1.1

  # Utils
  equatable: ^2.0.5
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true