// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJW3VoXr1XW4m4Rkl6c6r6kikJsVDKJsI',
    appId: '1:700606011798:web:34894b8492f6f64c0aa5b7',
    messagingSenderId: '700606011798',
    projectId: 'notes-app-80a09',
    authDomain: 'notes-app-80a09.firebaseapp.com',
    storageBucket: 'notes-app-80a09.firebasestorage.app',
    measurementId: 'G-WWCYGL2887',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtfXzdtTOOe_ntngHAy1HuyaWRTh9Ckc8',
    appId: '1:700606011798:android:79eb2a925bcfd42b0aa5b7',
    messagingSenderId: '700606011798',
    projectId: 'notes-app-80a09',
    storageBucket: 'notes-app-80a09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWq_XBCSNZz7DtHe0wlk_nSl4JTRv1bPg',
    appId: '1:700606011798:ios:8137c3f829e042900aa5b7',
    messagingSenderId: '700606011798',
    projectId: 'notes-app-80a09',
    storageBucket: 'notes-app-80a09.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJW3VoXr1XW4m4Rkl6c6r6kikJsVDKJsI',
    appId: '1:700606011798:web:4bebab1060274f5e0aa5b7',
    messagingSenderId: '700606011798',
    projectId: 'notes-app-80a09',
    authDomain: 'notes-app-80a09.firebaseapp.com',
    storageBucket: 'notes-app-80a09.firebasestorage.app',
    measurementId: 'G-0872X028QS',
  );

}